// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSHighlighter
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSHighlighter.6169e590-2d12-4e0c-8433-9c90427d0ec7";
        public const string Name = "Highlighter";
        public const string Description = @"Highlight parts of code to make them easier to see and find.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
