// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSHighlighter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSHighlighterPackageString = "bdb718d6-5369-48b4-9185-f27c969759b2";
        public static Guid guidVSHighlighterPackage = new Guid(guidVSHighlighterPackageString);

        public const string guidVSHighlighterPackageCmdSetString = "e4e74e85-16cd-49f4-bf71-66aa948975ad";
        public static Guid guidVSHighlighterPackageCmdSet = new Guid(guidVSHighlighterPackageCmdSetString);

        public const string guidImagesString = "d2da83db-1ef6-49f0-9670-7b237baa363b";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidCshtmlCodeEditorString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid guidCshtmlCodeEditor = new Guid(guidCshtmlCodeEditorString);

        public const string GuidVisualStudioXAMLWindowContextMenuString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid GuidVisualStudioXAMLWindowContextMenu = new Guid(GuidVisualStudioXAMLWindowContextMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int HighlightFuchsiaId = 0x0200;
        public const int HighlightGoldId = 0x0300;
        public const int CodeContextGroup = 0x1100;
        public const int CodeContextMenu = 0x1200;
        public const int bmpTurquoise = 0x0001;
        public const int bmpFuchsia = 0x0002;
        public const int bmpGold = 0x0003;
        public const int bmpLime = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int IDVisualStudioXAMLWindowContextMenu = 0x0103;
    }
}